name: blue_waves
description: Blue waves, a beach database.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.0
  dio: ^4.0.0
  firebase_analytics: ^9.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  firebase_crashlytics: ^2.2.0
  firebase_remote_config: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  get: ^4.3.8
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.5
  image_picker: ^0.8.0+3
  intl: ^0.17.0
  intl_utils: ^2.4.0
  lint: ^1.6.0
  logger: ^1.0.0
  lottie: ^1.0.0
  onesignal_flutter: ^3.2.3
  package_info: ^2.0.0
  permission_handler: ^8.1.1
  photo_view: ^0.13.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.0
  sentry_flutter: ^6.0.0
  string_extensions: ^0.4.0
  supabase_flutter: ^0.2.9
  url_launcher: ^6.0.2
  uuid: ^3.0.4
  wave: ^0.2.0
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/launcher.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  assets:
    - assets/images/
    - assets/launcher_icons/
    - map_styles.txt
    - map_styles_light.txt
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AdventPro
      fonts:
        - asset: fonts/AdventPro-Regular.ttf
        - asset: fonts/AdventPro-Bold.ttf
          weight: 700
        - asset: fonts/AdventPro-Thin.ttf
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en
